# Generated by Django 5.2.7 on 2025-10-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do paciente', max_length=255)),
                ('cpf', models.CharField(help_text='CPF no formato 000.000.000-00', max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(blank=True, help_text='Telefone com DDD (opcional)', max_length=20, null=True)),
                ('comorbidade', models.CharField(choices=[('Hipertensão', 'Hipertensão'), ('Diabetes', 'Diabetes'), ('Gestante', 'Gestante')], help_text='Comorbidade principal do paciente', max_length=50)),
                ('data_consulta', models.DateField(help_text='Data da consulta mais recente registrada.')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais (opcional)', null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
