# Generated by Django 5.2.7 on 2025-11-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço completo do paciente (opcional)', max_length=255, null=True),
        ),
    ]
