# Generated by Django 5.2.7 on 2025-11-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(default='Endereço não informado', help_text='Endereço completo do paciente', max_length=255),
            preserve_default=False,
        ),
    ]
