# Generated by Django 5.2.7 on 2025-12-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='comorbidade',
            field=models.CharField(choices=[('Hipertensão', 'Hipertensão'), ('Diabetes', 'Diabetes'), ('Gestante', 'Gestante')], help_text='Necessidade específica principal do paciente', max_length=50, verbose_name='Necessidade Específica'),
        ),
    ]
